version: "3"


dotenv:
    - ./environment/.version.env


tasks:
    manifest:update:
        cmds:
            - |
              jq                                                      \
                    --indent 4                                        \
                    --arg v "{{ .MOD_VERSION }}"                      \
                    '.version_number = $v'                            \
                    ./assets/manifest.template.json > ./manifest.json

    build:
        cmds:
            - echo $MOD_VERSION
            - |
              dotnet build                                               \
                    --configuration Release                              \
                    /p:MOD_version="\"{{.MOD_VERSION}}\""

    build:thunderstore:
        deps: [manifest:update, build]
        vars:
            ICON_PATH: ./assets/icon.png
            MANIFEST_PATH: ./manifest.json
            CHANGELOG_PATH: ./CHANGELOG.md
            README_PATH: ./README.md
            DLL_FILE: ./bin/Release/TeamUpgrades.dll
            SAVE_TO: "./bundles/bundle.zip"
        cmds:
            - |
              zip                     \
                -j {{ .SAVE_TO }}     \
                {{ .ICON_PATH      }} \
                {{ .MANIFEST_PATH  }} \
                {{ .CHANGELOG_PATH }} \
                {{ .DLL_FILE       }} \
                {{ .README_PATH    }}

