version: "3"


tasks:
    build:thunderstore:
        vars:
            ICON_PATH: ./assets/icon.png
            MANIFEST_PATH: ./manifest.json
            CHANGELOG_PATH: ./CHANGELOG.md
            README_PATH: ./README.md
            DLL_FILE: ./bin/Debug/ScalingPrices.dll
            SAVE_TO: "./bundles/bundle.zip"
        cmds:
            - |
              zip                     \
                -j {{ .SAVE_TO }}     \
                {{ .ICON_PATH      }} \
                {{ .MANIFEST_PATH  }} \
                {{ .CHANGELOG_PATH }} \
                {{ .DLL_FILE       }} \
                {{ .README_PATH    }}
